server:
    port: 8082 #启动端口
# SPRING PROFILES
spring:
    # DATASOURCE
    datasource:
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.2.4.85/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456


